version: "3.8"
services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: flaskdb
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flaskdb
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"

volumes:
  db_data:
